spring:
  data:
    redis:
      primary: redis1 # 默认 Redis 数据源为 redis1
      redis1:
        database: 1
        host: 39.99.241.16
        port: 6379
        password: d@OgcOQdvQ09
        #timeout: 6000ms  # 连接超时时长（毫秒）
      redis2:
        database: 2
        host: 39.99.241.16
        port: 6379
        password: d@OgcOQdvQ09
  #      redis2:
  #        database: 0
  #        host: 98.142.143.187
  #        port: 6379
  #        password: t7CzvhZ8u6QgT%D^44Xzh@Dv%ednUK

  kafka:
    bootstrap-servers: 39.99.241.16:9092
    consumer:
      auto-offset-reset: earliest  # 消费起始位置
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000 # 每次批量拉取消息数量
      enable-auto-commit: false # 禁用自动提交，改为手动提交
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      type: batch # 设置监听器类型为批量
    groupIdMap:
      "39.99.241.16": "order-group-a"
      "39.98.123.55": "order-group-b"
      "15.181.161.240": "order-group-c"
      "15.181.163.233": "order-group-d"
      "8.211.194.71": "order-group-e"
      "8.211.207.234": "order-group-f"
      "39.101.181.190": "order-group-g"

  datasource:
    dynamic:
      hikari: # Hikari 连接池全局配置
        connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
        minimum-idle: 2               # 最小空闲连接数
        maximum-pool-size: 10         # 最大连接数
        idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
        max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
        connection-test-query: SELECT 1
      primary: master
      datasource:
        master:
          # MySQL8
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.99.241.16:3306/follow-order-cp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 5v07DqL!F7333

        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.99.241.16:3306/copier_alan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 5v07DqL!F7333
  mqtt:
    host: tcp://localhost:1883
    username: maku
    password: maku
    clientId: maku_boot_service_dev
    default-topic: topic_default

